### ISSUE TITLE
Blur on round corners (Not a duplicate of issue #7)

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/LightlyShaders#12] opened 2021-07-23 14:35 UTC
I didn't want to open another issue as this already exists on #10 but since that was mistakingly closed by judging it as duplicate of #7, I had to reopen it but I'll explain why.

![image](https://user-images.githubusercontent.com/39316730/126796224-37a006ea-eb6d-465e-afa9-fa0c21470eb0.png)
This here is LightlyShaders with Lightly Widget Style and Window Decoration. Corner radius is set to 8px, the max setting. LightlyShaders.conf was also manually edited to have the exact same roundness because the slider on the GUI does not show what is the roundness
![image](https://user-images.githubusercontent.com/39316730/126796608-445dd710-934c-4e49-9070-8d81c04d616c.png)

The same happens with fully borderless and titlebarless windows but that are still affected by KWin and the window decoration
![image](https://user-images.githubusercontent.com/39316730/126797459-51ec6a14-2354-41a9-a1a4-8787eb759ceb.png)

As you can see, this is the setup expected with your forks of Breeze and this KWin shader. It is not ClassikStyles without the round corners option toggled on as this is Lightly. However, the blur around the corner is still there. It's not caused by the Window Decoration and I pointed that out on #10. Another user noticed the bug on the forum [Diolinux Plus](https://plus.diolinux.com.br/t/retirar-borda-transparente-das-janelas-no-kde/36548) and I noticed it is the same bug.

Now if this is caused by KWin and cannot be avoided, it's understandable but at least it could be added as known issue on the README.md

**Comment by Luwx** [comment] 2021-07-23 20:41
In your screenshot, the issue is caused by the infamous KWin bug https://bugs.kde.org/show_bug.cgi?id=395725  

Although visually similar, it is not the same as #10 or the other one you linked, they are not using the blur effect.

On a side note, since you are not using a titlebar in Konsole, the blur issue can be easily fixed in the Konsole code (compared to fixing 395725 that affect all decorations) by passing a rounded region to blur. Maybe you could open a issue here https://bugs.kde.org/enter_bug.cgi?product=konsole and ask if they could implement a "blur area corner radius" option.

**Comment by Luwx** [comment] 2021-07-23 20:49
https://plus.diolinux.com.br/uploads/default/original/3X/b/f/bf601895723e8227ed99aa98c4f11daf6a50e462.jpeg

The square bottom corners seems to be a classikStyles issue.

https://plus.diolinux.com.br/uploads/default/original/3X/2/6/26fc234f279236acbe98e860f53006a028134e30.jpeg

The effect corner radius is bigger than the decoration corner radius.

**Comment by Luwx** [comment] 2021-07-23 20:50
I'll update the README

**Closed by Luwx** 2021-07-23 20:49 UTC
