### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by nazar2sfive** [Luwx/LightlyShaders#18] opened 2021-08-28 06:32 UTC
```
/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h:125:20: note: declared here
  125 |     QVector<QRect> rects() const;
      |                    ^~~~~
/home/android/Downloads/Lightly/build/LightlyShaders/lightlyshaders.cpp: At global scope:
/home/android/Downloads/Lightly/build/LightlyShaders/lightlyshaders.cpp:235:13: warning: ‘bool hasShadow(KWin::WindowQuadList&)’ defined but not used [-Wunused-function]
  235 | static bool hasShadow(KWin::WindowQuadList &qds)
      |             ^~~~~~~~~
make[2]: *** [CMakeFiles/kwin4_effect_lightlyshaders.dir/build.make:76: CMakeFiles/kwin4_effect_lightlyshaders.dir/lightlyshaders.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:669: CMakeFiles/kwin4_effect_lightlyshaders.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

**Comment by Luwx** [comment] 2021-09-03 04:39
Duplicate of https://github.com/Luwx/LightlyShaders/issues/17.

**Closed by Luwx** 2021-09-03 04:39 UTC
